services:
#    omer_score.example:
#        class: Omer\ScoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    omer_score.admin.criterion:
        class: Omer\ScoreBundle\Admin\CriterionAdmin
        arguments: [~, Omer\ScoreBundle\Entity\Criterion, OmerScoreBundle:CriterionAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'label.group.scoring', label: 'admin.label.criterion' }
        calls:
            - [ setTranslationDomain, [OmerScoreBundle] ]
            # - [ setTokenStorage, ['@security.token_storage'] ]

    omer_score.admin.point:
        class: Omer\ScoreBundle\Admin\PointAdmin
        arguments: [~, Omer\ScoreBundle\Entity\Point, OmerScoreBundle:PointAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'label.group.scoring', label: Point, show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, [OmerScoreBundle] ]

    omer_score.admin.score:
        class: Omer\ScoreBundle\Admin\ScoreAdmin
        arguments: [~, Omer\ScoreBundle\Entity\Score, OmerScoreBundle:ScoreAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'label.group.scoring', label: Score }
        calls:
            - [ setTranslationDomain, [OmerScoreBundle] ]
