omer_competition:
    resource: "@OmerCompetitionBundle/Controller/"
    type:     annotation
    prefix:   /

omer_team:
    resource: "@OmerTeamBundle/Controller/"
    type:     annotation
    prefix:   /

omer_user:
    resource: "@OmerUserBundle/Controller/"
    type:     annotation
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#homepage:
#    path: /
#    defaults: { _controller: OmerTeamBundle:Default:index }

admin_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting


